name: setup
description: 依照 nvmrc 创建 node 环境

runs:
  using: composite
  steps:
    - run: sudo timedatectl set-timezone Asia/Shanghai
      shell: bash
    - run: timedatectl
      shell: bash
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc
        cache: pnpm
    - run: corepack enable
      shell: bash
    - run: pnpm i
      shell: bash

